apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/base 
      sourceRef:
        kind: GitRepository
        name: my-repo
        namespace: flux-system