apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/gateway_ingress 
      sourceRef:
        kind: GitRepository
        name: my-repo
        namespace: flux-system
  values:
    # service:
    #   loadBalancerIP: 127.0.0.1
    image: istio/proxyv2:1.25.2