apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/istio-control/istio-discovery/ 
      sourceRef:
        kind: GitRepository
        name: my-repo
        namespace: flux-system