apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: busybox:latest
        imagePullPolicy: Always
        name: test
        command: ['sh', '-c', 'while true; do date; sleep 3; done']
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test
spec:
  selector:
    app.kubernetes.io/name: test
  ports:
    - protocol: TCP
      port: 15021
      targetPort: 15021
      name: status
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 31400
      targetPort: 31400
      name: tcp
    - protocol: TCP
      port: 15443
      targetPort: 15443
      name: tls

